# frontend-k8s.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: nguyengoctu/frontend:1.0.0
        ports:
        - containerPort: 7009
        env:
        - name: PORT
          value: "7009"
        - name: DISABLE_PROFILER
          value: "1"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:7000"
        - name: PRODUCT_CATALOG_SERVICE_ADDR  
          value: "product-catalog-service:7002"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:7003"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendation-service:7005"
        - name: CART_SERVICE_ADDR
          value: "cart-service:7006"
        - name: AD_SERVICE_ADDR
          value: "ad-service:7007"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkout-service:7008"
        - name: SHOPPING_ASSISTANT_SERVICE_ADDR
          value: "localhost:9999"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - port: 7009
      targetPort: 7009
  type: ClusterIP